name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.1"
          gleam-version: "0.32.0-rc2"
          rebar3-version: "3"

      # Check formatting
      - run: gleam format --check backend/src backend/test analysis/src analysis/test

      # Install dependencies
      - run: cd analysis && gleam deps download
      - run: cd backend && gleam deps download
      - run: cd frontend && gleam deps download && npm ci

      # Run tests
      - run: cd analysis && gleam test
      - run: cd backend && gleam test
      - run: cd frontend && gleam test
